### ISSUE TITLE
After upgrade to 1.4 JS error

### ISSUE THREAD

**Issue by reficul** [roundcube/roundcubemail#7030]
`TypeError: rcmail[d].enable_checkbox_selection is not a function. (In 'rcmail[d].enable_checkbox_selection()', 'rcmail[d].enable_checkbox_selection' is undefined)`

All buttons on roundcube are disabled.
What can I do?

**Comment by alecpl** [comment]
What plugins are you using? Try to disable them.

**Comment by reficul** [comment]
```
'archive',
'zipdownload',
'managesieve',
'password',
```
I tried to remove them from the config but nothing has changed. Is there a way to force/overwrite current installation or downgrade it?

**Comment by alecpl** [comment]
Then something's wrong with your update or caching issue. Make sure the app is using proper program/js/list.js file.

**Comment by reficul** [comment]
I overwrite all JS/plugins and skins folder with 1.4 package downloaded here. 
But problem not solved. I give you some more info, so maybe you can help me figure out where to look.

list of oddities detected:
1. a 404 error in the console, looking for blank.tif but 1.4 served with blank.tiff in program->resources

2. With larry skin, in send mail window:
![Schermata 2019-11-13 alle 14 53 25](https://user-images.githubusercontent.com/1073883/68769972-8f8a8d00-0625-11ea-8eb9-4238ef8e408c.png)
an upload field (select file) under the toolbar, this is the html of the field

`<input multiple="" id="uploadformInput" type="file" name="_attachments[]" onchange="rcmail.command('send-attachment', this.form); this.value=null" class="smart-upload" tabindex="-1">`

3. With elastic skin all buttons are set as disabled, I need to remove "disabled" from inspector to be able to change theme or save something.

![Schermata 2019-11-13 alle 14 44 16](https://user-images.githubusercontent.com/1073883/68770152-e85a2580-0625-11ea-9722-5be48f84273e.png)

**Comment by alecpl** [comment]
> I overwrite all JS/plugins and skins folder with 1.4 package downloaded here.
What with the rest of folders? Did you used update script? It really looks like it's using some files from old version or sth like that.

**Comment by reficul** [comment]
Yes you're right, it's a goddamn cache problem. For example I’ve jquery 3.x in program/js and browser still show 2.x. Thanks and sorry for the waste of time.
