### ISSUE TITLE
app.js shrink is failing: ECMASCRIPT6 features are used

### ISSUE THREAD

**Issue by X-dark** [roundcube/roundcubemail#7466]
app.js minimization is failing with the following error:

```
bin/../program/js/app.js:2166: ERROR - [JSC_LANGUAGE_FEATURE] This language feature is only supported for ECMASCRIPT6 mode or better: default parameter.
  2166|   this.add_message_row = function(uid, cols, flags, attop, layout = this.env.layout)
```

This has been introduced with #7287

**Comment by alecpl** [comment]
@johndoh could you rewrite your changes to not use ECMASCRIPT6 ?
