### ISSUE TITLE
1.3.0: No mail body input field visible in composer with default skin

### ISSUE THREAD

**Issue by markuswernig** [roundcube/roundcubemail#5822]
After upgrading to 1.3.0 users can no longer compose new messages when using the default ("Classic") 
interface skin.

Instead of the input area for the mail text, there is only an overly large attachments pane.
When switching to the larry skin, the input field is there again.

Happens in Firefox 54.0 and Chrome 59.0.3071.109, both on Linux (no other browser/OS tested).

![screenshot_20170627_144138](https://user-images.githubusercontent.com/29691702/27588117-4e73cc2c-5b47-11e7-9ada-7494495e2013.png)

**Comment by markuswernig** [comment]
OK, here's a quick hack as a workaround:

In skins/classic/mail.min.css, edit the properties for `#compose-attachments` (around column 19402 on the line) and change `left:0;` to `left: 87%`. (87 is just the value best suited for my screen resolution).

This does neither scale nicely nor is it a solution. But it will stop the attachment pane from hiding the `compose-body` textarea.

**Comment by alecpl** [comment]
Please, check browser console for errors.

**Comment by markuswernig** [comment]
Ah yes:

<pre>
jQuery.Deferred exception: a.indexOf is not a function r.fn.load@https://server.host.name/program/js/jquery.min.js?s=1498503424:38:18892
@https://server.host.name/plugins/contextmenu/contextmenu.js?s=1429340030:902:4
triggerEvent@https://server.host.name/program/js/common.min.js?s=1498503408:40:211
rcube_webmail/this.init@https://server.host.name/program/js/app.min.js?s=1498503408:64:257
@https://server.host.name/?_task=mail&_mbox=INBOX:1190:1
j@https://server.host.name/program/js/jquery.min.js?s=1498503424:36:29997
g/</k<@https://server.host.name/program/js/jquery.min.js?s=1498503424:36:30313
 undefined
</pre>

**Comment by alecpl** [comment]
So, contextmenu issue? Could you try without this plugin?

**Comment by markuswernig** [comment]
Ah, my bad! I had not updated the contextmenu plugin (was still at 2.1.2) after the server upgrade.

After upgrading the plugin to version 2.3, it now works without problems.

Thanks for the hint!
